// All poses define joint positions relative to the hip anchor point.
// X is flipped based on facing direction.
// Positive Y is down, negative Y is up.

const IDLE_BASE = {
  head:      { x: 0, y: -90 },
  neck:      { x: 0, y: -72 },
  hip:       { x: 0, y: 0 },
  shoulderL: { x: -14, y: -70 },
  shoulderR: { x: 14, y: -70 },
  elbowL:    { x: -22, y: -50 },
  elbowR:    { x: 22, y: -50 },
  handL:     { x: -18, y: -35 },
  handR:     { x: 18, y: -35 },
  kneeL:     { x: -10, y: 25 },
  kneeR:     { x: 10, y: 25 },
  footL:     { x: -15, y: 50 },
  footR:     { x: 15, y: 50 },
};

export const POSES = {
  IDLE: [
    IDLE_BASE,
    {
      ...IDLE_BASE,
      head:   { x: 0, y: -88 },
      neck:   { x: 0, y: -70 },
      handL:  { x: -20, y: -33 },
      handR:  { x: 20, y: -33 },
    },
  ],

  WALK_FORWARD: [
    {
      head:      { x: 2, y: -90 },
      neck:      { x: 2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -12, y: -70 },
      shoulderR: { x: 16, y: -70 },
      elbowL:    { x: -25, y: -55 },
      elbowR:    { x: 25, y: -45 },
      handL:     { x: -20, y: -40 },
      handR:     { x: 22, y: -30 },
      kneeL:     { x: -5, y: 22 },
      kneeR:     { x: 15, y: 22 },
      footL:     { x: -10, y: 50 },
      footR:     { x: 22, y: 50 },
    },
    {
      head:      { x: 2, y: -90 },
      neck:      { x: 2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -12, y: -70 },
      shoulderR: { x: 16, y: -70 },
      elbowL:    { x: -18, y: -45 },
      elbowR:    { x: 20, y: -55 },
      handL:     { x: -15, y: -30 },
      handR:     { x: 18, y: -40 },
      kneeL:     { x: -15, y: 22 },
      kneeR:     { x: 5, y: 22 },
      footL:     { x: -22, y: 50 },
      footR:     { x: 10, y: 50 },
    },
  ],

  WALK_BACKWARD: [
    {
      head:      { x: -2, y: -90 },
      neck:      { x: -2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -16, y: -70 },
      shoulderR: { x: 12, y: -70 },
      elbowL:    { x: -20, y: -45 },
      elbowR:    { x: 18, y: -55 },
      handL:     { x: -18, y: -30 },
      handR:     { x: 15, y: -40 },
      kneeL:     { x: -15, y: 22 },
      kneeR:     { x: 5, y: 22 },
      footL:     { x: -22, y: 50 },
      footR:     { x: 10, y: 50 },
    },
    {
      head:      { x: -2, y: -90 },
      neck:      { x: -2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -16, y: -70 },
      shoulderR: { x: 12, y: -70 },
      elbowL:    { x: -25, y: -55 },
      elbowR:    { x: 25, y: -45 },
      handL:     { x: -22, y: -40 },
      handR:     { x: 22, y: -30 },
      kneeL:     { x: -5, y: 22 },
      kneeR:     { x: 15, y: 22 },
      footL:     { x: -10, y: 50 },
      footR:     { x: 22, y: 50 },
    },
  ],

  JUMP: [
    {
      head:      { x: 0, y: -85 },
      neck:      { x: 0, y: -68 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -66 },
      shoulderR: { x: 14, y: -66 },
      elbowL:    { x: -24, y: -75 },
      elbowR:    { x: 24, y: -75 },
      handL:     { x: -20, y: -85 },
      handR:     { x: 20, y: -85 },
      kneeL:     { x: -16, y: 15 },
      kneeR:     { x: 16, y: 15 },
      footL:     { x: -20, y: 35 },
      footR:     { x: 20, y: 35 },
    },
  ],

  PUNCH: [
    // Windup
    {
      head:      { x: -2, y: -90 },
      neck:      { x: -2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -22, y: -50 },
      elbowR:    { x: 8, y: -55 },
      handL:     { x: -18, y: -35 },
      handR:     { x: 0, y: -50 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 10, y: 25 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 15, y: 50 },
    },
    // Active hit frame
    {
      head:      { x: 4, y: -90 },
      neck:      { x: 4, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -22, y: -50 },
      elbowR:    { x: 35, y: -65 },
      handL:     { x: -18, y: -35 },
      handR:     { x: 55, y: -65 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 12, y: 25 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 15, y: 50 },
    },
    // Recovery
    {
      head:      { x: 2, y: -90 },
      neck:      { x: 2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -22, y: -50 },
      elbowR:    { x: 25, y: -55 },
      handL:     { x: -18, y: -35 },
      handR:     { x: 30, y: -45 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 10, y: 25 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 15, y: 50 },
    },
  ],

  KICK: [
    // Windup - leg pulls up
    {
      head:      { x: -4, y: -90 },
      neck:      { x: -4, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -22, y: -50 },
      elbowR:    { x: 22, y: -50 },
      handL:     { x: -18, y: -35 },
      handR:     { x: 18, y: -35 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 20, y: 5 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 15, y: 15 },
    },
    // Active hit frame - leg extended
    {
      head:      { x: -2, y: -90 },
      neck:      { x: -2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -25, y: -55 },
      elbowR:    { x: 20, y: -55 },
      handL:     { x: -22, y: -40 },
      handR:     { x: 16, y: -40 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 35, y: 5 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 65, y: 0 },
    },
    // Recovery
    {
      head:      { x: -2, y: -90 },
      neck:      { x: -2, y: -72 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -70 },
      shoulderR: { x: 14, y: -70 },
      elbowL:    { x: -22, y: -50 },
      elbowR:    { x: 22, y: -50 },
      handL:     { x: -18, y: -35 },
      handR:     { x: 18, y: -35 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 18, y: 15 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 25, y: 40 },
    },
  ],

  SPECIAL: [
    // Windup - dramatic crouch
    {
      head:      { x: -4, y: -80 },
      neck:      { x: -4, y: -62 },
      hip:       { x: 0, y: 5 },
      shoulderL: { x: -16, y: -60 },
      shoulderR: { x: 16, y: -60 },
      elbowL:    { x: -28, y: -45 },
      elbowR:    { x: 10, y: -50 },
      handL:     { x: -30, y: -30 },
      handR:     { x: 0, y: -45 },
      kneeL:     { x: -14, y: 28 },
      kneeR:     { x: 14, y: 28 },
      footL:     { x: -20, y: 50 },
      footR:     { x: 18, y: 50 },
    },
    // Active - lunging forward
    {
      head:      { x: 15, y: -85 },
      neck:      { x: 12, y: -68 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -5, y: -66 },
      shoulderR: { x: 22, y: -66 },
      elbowL:    { x: -10, y: -50 },
      elbowR:    { x: 45, y: -60 },
      handL:     { x: -5, y: -35 },
      handR:     { x: 65, y: -55 },
      kneeL:     { x: -18, y: 20 },
      kneeR:     { x: 20, y: 15 },
      footL:     { x: -30, y: 50 },
      footR:     { x: 30, y: 50 },
    },
    // Recovery
    {
      head:      { x: 5, y: -88 },
      neck:      { x: 4, y: -70 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -12, y: -68 },
      shoulderR: { x: 16, y: -68 },
      elbowL:    { x: -20, y: -50 },
      elbowR:    { x: 30, y: -52 },
      handL:     { x: -16, y: -35 },
      handR:     { x: 35, y: -40 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 12, y: 25 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 16, y: 50 },
    },
  ],

  BLOCK: [
    {
      head:      { x: -4, y: -88 },
      neck:      { x: -4, y: -70 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -14, y: -68 },
      shoulderR: { x: 14, y: -68 },
      elbowL:    { x: -8, y: -52 },
      elbowR:    { x: 8, y: -52 },
      handL:     { x: 2, y: -65 },
      handR:     { x: 6, y: -42 },
      kneeL:     { x: -12, y: 26 },
      kneeR:     { x: 12, y: 26 },
      footL:     { x: -16, y: 50 },
      footR:     { x: 16, y: 50 },
    },
  ],

  HIT: [
    {
      head:      { x: -8, y: -88 },
      neck:      { x: -6, y: -70 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -16, y: -68 },
      shoulderR: { x: 10, y: -68 },
      elbowL:    { x: -28, y: -55 },
      elbowR:    { x: 5, y: -50 },
      handL:     { x: -30, y: -40 },
      handR:     { x: -5, y: -38 },
      kneeL:     { x: -8, y: 26 },
      kneeR:     { x: 12, y: 26 },
      footL:     { x: -12, y: 50 },
      footR:     { x: 18, y: 50 },
    },
  ],

  KO: [
    // Falling
    {
      head:      { x: -15, y: -75 },
      neck:      { x: -10, y: -58 },
      hip:       { x: 0, y: 5 },
      shoulderL: { x: -18, y: -55 },
      shoulderR: { x: 2, y: -55 },
      elbowL:    { x: -30, y: -40 },
      elbowR:    { x: -8, y: -38 },
      handL:     { x: -35, y: -25 },
      handR:     { x: -15, y: -22 },
      kneeL:     { x: -5, y: 28 },
      kneeR:     { x: 15, y: 28 },
      footL:     { x: -10, y: 50 },
      footR:     { x: 22, y: 50 },
    },
    // On the ground
    {
      head:      { x: -35, y: 30 },
      neck:      { x: -25, y: 35 },
      hip:       { x: 0, y: 40 },
      shoulderL: { x: -28, y: 32 },
      shoulderR: { x: -22, y: 38 },
      elbowL:    { x: -35, y: 42 },
      elbowR:    { x: -15, y: 45 },
      handL:     { x: -42, y: 48 },
      handR:     { x: -8, y: 50 },
      kneeL:     { x: 15, y: 38 },
      kneeR:     { x: 20, y: 42 },
      footL:     { x: 30, y: 45 },
      footR:     { x: 38, y: 48 },
    },
  ],

  VICTORY: [
    {
      head:      { x: 0, y: -95 },
      neck:      { x: 0, y: -75 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -73 },
      shoulderR: { x: 14, y: -73 },
      elbowL:    { x: -22, y: -88 },
      elbowR:    { x: 22, y: -88 },
      handL:     { x: -28, y: -105 },
      handR:     { x: 28, y: -105 },
      kneeL:     { x: -10, y: 25 },
      kneeR:     { x: 10, y: 25 },
      footL:     { x: -15, y: 50 },
      footR:     { x: 15, y: 50 },
    },
  ],
};

// Helper to interpolate between two poses
export function lerpPose(poseA, poseB, t) {
  const result = {};
  for (const joint in poseA) {
    result[joint] = {
      x: poseA[joint].x + (poseB[joint].x - poseA[joint].x) * t,
      y: poseA[joint].y + (poseB[joint].y - poseA[joint].y) * t,
    };
  }
  return result;
}
