// Each character has unique stats and a special move type.
// Special types are implemented in Fighter.updateState().

export const FIGHTERS = [
  {
    id: 'swift',
    name: 'Swift',
    color: 0xffffff,
    description: 'Balanced fighter with a quick lunge.',
    moveSpeed: 300,
    jumpVelocity: -650,
    punchDamage: 8,
    punchRange: 60,
    kickDamage: 14,
    kickRange: 80,
    specialDamage: 22,
    specialRange: 100,
    specialType: 'lunge',
    specialName: 'Dash Strike',
  },
  {
    id: 'titan',
    name: 'Titan',
    color: 0x00ffff,
    description: 'Slow powerhouse. Ground pound shakes the arena.',
    moveSpeed: 220,
    jumpVelocity: -520,
    punchDamage: 11,
    punchRange: 65,
    kickDamage: 19,
    kickRange: 85,
    specialDamage: 28,
    specialRange: 120,
    specialType: 'groundPound',
    specialName: 'Ground Pound',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    color: 0xbb44ff,
    description: 'Fragile but lightning fast. Teleports behind foes.',
    moveSpeed: 380,
    jumpVelocity: -700,
    punchDamage: 7,
    punchRange: 55,
    kickDamage: 12,
    kickRange: 75,
    specialDamage: 18,
    specialRange: 60,
    specialType: 'teleport',
    specialName: 'Shadow Step',
    maxHealth: 80,
  },
  {
    id: 'blaze',
    name: 'Blaze',
    color: 0xff6600,
    description: 'Aggressive brawler with a fiery uppercut.',
    moveSpeed: 280,
    jumpVelocity: -620,
    punchDamage: 9,
    punchRange: 58,
    kickDamage: 15,
    kickRange: 78,
    specialDamage: 24,
    specialRange: 70,
    specialType: 'uppercut',
    specialName: 'Fire Uppercut',
  },
  {
    id: 'frost',
    name: 'Frost',
    color: 0x66ccff,
    description: 'Cool and collected. Ice slide covers distance fast.',
    moveSpeed: 260,
    jumpVelocity: -600,
    punchDamage: 8,
    punchRange: 60,
    kickDamage: 14,
    kickRange: 80,
    specialDamage: 20,
    specialRange: 130,
    specialType: 'slide',
    specialName: 'Ice Slide',
  },
  {
    id: 'thunder',
    name: 'Thunder',
    color: 0xffff00,
    description: 'Electrifying strikes. Lightning drop from above.',
    moveSpeed: 270,
    jumpVelocity: -680,
    punchDamage: 9,
    punchRange: 60,
    kickDamage: 16,
    kickRange: 82,
    specialDamage: 26,
    specialRange: 90,
    specialType: 'lightningDrop',
    specialName: 'Lightning Drop',
  },
  {
    id: 'viper',
    name: 'Viper',
    color: 0x44ff44,
    description: 'Quick multi-hit combos. Rapid dash flurry.',
    moveSpeed: 330,
    jumpVelocity: -640,
    punchDamage: 6,
    punchRange: 55,
    kickDamage: 10,
    kickRange: 70,
    specialDamage: 8,
    specialRange: 80,
    specialType: 'flurry',
    specialName: 'Viper Flurry',
    specialHits: 4,
  },
  {
    id: 'golem',
    name: 'Golem',
    color: 0xaa8855,
    description: 'Immovable wall. Absorbs a hit during special.',
    moveSpeed: 180,
    jumpVelocity: -450,
    punchDamage: 13,
    punchRange: 70,
    kickDamage: 22,
    kickRange: 90,
    specialDamage: 30,
    specialRange: 90,
    specialType: 'armorSmash',
    specialName: 'Armor Smash',
    maxHealth: 120,
  },
  {
    id: 'phantom',
    name: 'Phantom',
    color: 0xddddff,
    description: 'Floaty and evasive. Spinning whirlwind attack.',
    moveSpeed: 290,
    jumpVelocity: -750,
    punchDamage: 7,
    punchRange: 55,
    kickDamage: 12,
    kickRange: 75,
    specialDamage: 16,
    specialRange: 110,
    specialType: 'whirlwind',
    specialName: 'Whirlwind',
  },
  {
    id: 'nova',
    name: 'Nova',
    color: 0xff3366,
    description: 'Glass cannon. Massive explosive burst.',
    moveSpeed: 260,
    jumpVelocity: -600,
    punchDamage: 10,
    punchRange: 58,
    kickDamage: 16,
    kickRange: 78,
    specialDamage: 38,
    specialRange: 140,
    specialType: 'explosion',
    specialName: 'Nova Burst',
    maxHealth: 70,
  },
];

// Keep backwards-compatible exports for existing code
export const FIGHTER_DATA = {
  balanced: FIGHTERS[0],
  heavy: FIGHTERS[1],
};
