// All poses define joint positions relative to the hip anchor point.
// Positive X = forward (facing right), flipped by renderer.
// Positive Y = down, negative Y = up.
// Hip at (0,0). Feet ~60, Head ~-100. Longer limbs for dramatic look.
// Looping states (IDLE, WALK, VICTORY) use frame 3 ≈ frame 1 for smooth wrap.

export const POSES = {
  // === IDLE: Fighting stance with rhythmic bounce ===
  IDLE: [
    // Frame 0: UP — tall guard
    {
      head:      { x: 3, y: -100 },
      neck:      { x: 2, y: -82 },
      hip:       { x: 0, y: -2 },
      shoulderL: { x: -15, y: -80 },
      shoulderR: { x: 15, y: -80 },
      elbowL:    { x: -3, y: -62 },
      elbowR:    { x: 26, y: -66 },
      handL:     { x: 12, y: -80 },
      handR:     { x: 32, y: -84 },
      kneeL:     { x: -18, y: 24 },
      kneeR:     { x: 18, y: 24 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 22, y: 60 },
    },
    // Frame 1: MID — transitioning down
    {
      head:      { x: 3, y: -97 },
      neck:      { x: 2, y: -79 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -15, y: -77 },
      shoulderR: { x: 15, y: -77 },
      elbowL:    { x: -5, y: -59 },
      elbowR:    { x: 24, y: -63 },
      handL:     { x: 10, y: -77 },
      handR:     { x: 30, y: -81 },
      kneeL:     { x: -18, y: 27 },
      kneeR:     { x: 18, y: 27 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 22, y: 60 },
    },
    // Frame 2: DOWN — compressed, knees bent
    {
      head:      { x: 3, y: -94 },
      neck:      { x: 2, y: -76 },
      hip:       { x: 0, y: 6 },
      shoulderL: { x: -15, y: -74 },
      shoulderR: { x: 15, y: -74 },
      elbowL:    { x: -7, y: -56 },
      elbowR:    { x: 22, y: -60 },
      handL:     { x: 8, y: -74 },
      handR:     { x: 28, y: -78 },
      kneeL:     { x: -18, y: 30 },
      kneeR:     { x: 18, y: 30 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 22, y: 60 },
    },
    // Frame 3: MID — transitioning up (≈ frame 1 for smooth loop)
    {
      head:      { x: 3, y: -97 },
      neck:      { x: 2, y: -79 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -15, y: -77 },
      shoulderR: { x: 15, y: -77 },
      elbowL:    { x: -5, y: -59 },
      elbowR:    { x: 24, y: -63 },
      handL:     { x: 10, y: -77 },
      handR:     { x: 30, y: -81 },
      kneeL:     { x: -18, y: 27 },
      kneeR:     { x: 18, y: 27 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 22, y: 60 },
    },
  ],

  // === WALK FORWARD: Aggressive advance with arm-leg opposition ===
  WALK_FORWARD: [
    // Frame 0: Right leg forward, left arm forward
    {
      head:      { x: 8, y: -98 },
      neck:      { x: 6, y: -80 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -12, y: -78 },
      shoulderR: { x: 16, y: -78 },
      elbowL:    { x: 8, y: -64 },
      elbowR:    { x: 10, y: -58 },
      handL:     { x: 20, y: -74 },
      handR:     { x: 6, y: -44 },
      kneeL:     { x: -8, y: 26 },
      kneeR:     { x: 26, y: 20 },
      footL:     { x: -14, y: 60 },
      footR:     { x: 36, y: 60 },
    },
    // Frame 1: Passing — narrow, upright
    {
      head:      { x: 5, y: -100 },
      neck:      { x: 4, y: -82 },
      hip:       { x: 0, y: -2 },
      shoulderL: { x: -14, y: -80 },
      shoulderR: { x: 14, y: -80 },
      elbowL:    { x: -2, y: -64 },
      elbowR:    { x: 24, y: -66 },
      handL:     { x: 12, y: -78 },
      handR:     { x: 30, y: -80 },
      kneeL:     { x: -6, y: 26 },
      kneeR:     { x: 10, y: 26 },
      footL:     { x: -8, y: 60 },
      footR:     { x: 14, y: 60 },
    },
    // Frame 2: Left leg forward, right arm forward
    {
      head:      { x: 8, y: -98 },
      neck:      { x: 6, y: -80 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -12, y: -78 },
      shoulderR: { x: 16, y: -78 },
      elbowL:    { x: -14, y: -56 },
      elbowR:    { x: 30, y: -66 },
      handL:     { x: -8, y: -42 },
      handR:     { x: 36, y: -78 },
      kneeL:     { x: -26, y: 20 },
      kneeR:     { x: 8, y: 26 },
      footL:     { x: -36, y: 60 },
      footR:     { x: 14, y: 60 },
    },
    // Frame 3: Passing (≈ frame 1)
    {
      head:      { x: 5, y: -100 },
      neck:      { x: 4, y: -82 },
      hip:       { x: 0, y: -2 },
      shoulderL: { x: -14, y: -80 },
      shoulderR: { x: 14, y: -80 },
      elbowL:    { x: -2, y: -64 },
      elbowR:    { x: 24, y: -66 },
      handL:     { x: 12, y: -78 },
      handR:     { x: 30, y: -80 },
      kneeL:     { x: -6, y: 26 },
      kneeR:     { x: 10, y: 26 },
      footL:     { x: -8, y: 60 },
      footR:     { x: 14, y: 60 },
    },
  ],

  // === WALK BACKWARD: Cautious defensive retreat ===
  WALK_BACKWARD: [
    // Frame 0: Left foot back
    {
      head:      { x: -4, y: -96 },
      neck:      { x: -3, y: -78 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -16, y: -76 },
      shoulderR: { x: 12, y: -76 },
      elbowL:    { x: -6, y: -62 },
      elbowR:    { x: 20, y: -66 },
      handL:     { x: 6, y: -76 },
      handR:     { x: 26, y: -80 },
      kneeL:     { x: -26, y: 22 },
      kneeR:     { x: 6, y: 26 },
      footL:     { x: -36, y: 60 },
      footR:     { x: 10, y: 60 },
    },
    // Frame 1: Narrow
    {
      head:      { x: -2, y: -98 },
      neck:      { x: -1, y: -80 },
      hip:       { x: 0, y: 1 },
      shoulderL: { x: -14, y: -78 },
      shoulderR: { x: 14, y: -78 },
      elbowL:    { x: -4, y: -64 },
      elbowR:    { x: 24, y: -66 },
      handL:     { x: 10, y: -78 },
      handR:     { x: 30, y: -82 },
      kneeL:     { x: -10, y: 26 },
      kneeR:     { x: 10, y: 26 },
      footL:     { x: -14, y: 60 },
      footR:     { x: 14, y: 60 },
    },
    // Frame 2: Right foot back
    {
      head:      { x: -4, y: -96 },
      neck:      { x: -3, y: -78 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -16, y: -76 },
      shoulderR: { x: 12, y: -76 },
      elbowL:    { x: -8, y: -60 },
      elbowR:    { x: 22, y: -64 },
      handL:     { x: 8, y: -74 },
      handR:     { x: 28, y: -78 },
      kneeL:     { x: -6, y: 26 },
      kneeR:     { x: 26, y: 22 },
      footL:     { x: -10, y: 60 },
      footR:     { x: 36, y: 60 },
    },
    // Frame 3: Narrow (≈ frame 1)
    {
      head:      { x: -2, y: -98 },
      neck:      { x: -1, y: -80 },
      hip:       { x: 0, y: 1 },
      shoulderL: { x: -14, y: -78 },
      shoulderR: { x: 14, y: -78 },
      elbowL:    { x: -4, y: -64 },
      elbowR:    { x: 24, y: -66 },
      handL:     { x: 10, y: -78 },
      handR:     { x: 30, y: -82 },
      kneeL:     { x: -10, y: 26 },
      kneeR:     { x: 10, y: 26 },
      footL:     { x: -14, y: 60 },
      footR:     { x: 14, y: 60 },
    },
  ],

  // === JUMP: Ascent → Apex → Descent ===
  JUMP: [
    // Ascending: tucked, arms up
    {
      head:      { x: 0, y: -96 },
      neck:      { x: 0, y: -78 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -14, y: -76 },
      shoulderR: { x: 14, y: -76 },
      elbowL:    { x: -22, y: -90 },
      elbowR:    { x: 22, y: -90 },
      handL:     { x: -18, y: -105 },
      handR:     { x: 18, y: -105 },
      kneeL:     { x: -20, y: 12 },
      kneeR:     { x: 20, y: 12 },
      footL:     { x: -26, y: 36 },
      footR:     { x: 26, y: 36 },
    },
    // Apex: spread, dramatic silhouette
    {
      head:      { x: 0, y: -102 },
      neck:      { x: 0, y: -84 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -16, y: -82 },
      shoulderR: { x: 16, y: -82 },
      elbowL:    { x: -34, y: -74 },
      elbowR:    { x: 34, y: -74 },
      handL:     { x: -44, y: -62 },
      handR:     { x: 44, y: -62 },
      kneeL:     { x: -24, y: 16 },
      kneeR:     { x: 24, y: 16 },
      footL:     { x: -34, y: 42 },
      footR:     { x: 34, y: 42 },
    },
    // Descending: legs forward, bracing for landing
    {
      head:      { x: 3, y: -94 },
      neck:      { x: 2, y: -76 },
      hip:       { x: 0, y: 4 },
      shoulderL: { x: -14, y: -74 },
      shoulderR: { x: 14, y: -74 },
      elbowL:    { x: -6, y: -62 },
      elbowR:    { x: 24, y: -64 },
      handL:     { x: 8, y: -74 },
      handR:     { x: 30, y: -76 },
      kneeL:     { x: -16, y: 22 },
      kneeR:     { x: 16, y: 22 },
      footL:     { x: -22, y: 50 },
      footR:     { x: 22, y: 50 },
    },
  ],

  // === PUNCH: Devastating jab — coil, snap, extend, recover ===
  PUNCH: [
    // Frame 0: COIL — body rotates away, fist cocks back
    {
      head:      { x: -8, y: -98 },
      neck:      { x: -6, y: -80 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -20, y: -78 },
      shoulderR: { x: 8, y: -78 },
      elbowL:    { x: -10, y: -62 },
      elbowR:    { x: -6, y: -60 },
      handL:     { x: 6, y: -76 },
      handR:     { x: -12, y: -52 },
      kneeL:     { x: -16, y: 26 },
      kneeR:     { x: 20, y: 24 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 26, y: 60 },
    },
    // Frame 1: SNAP — fist shoots forward, body uncoils
    {
      head:      { x: 10, y: -98 },
      neck:      { x: 8, y: -80 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -8, y: -78 },
      shoulderR: { x: 22, y: -78 },
      elbowL:    { x: -4, y: -62 },
      elbowR:    { x: 48, y: -76 },
      handL:     { x: 8, y: -74 },
      handR:     { x: 72, y: -76 },
      kneeL:     { x: -16, y: 26 },
      kneeR:     { x: 18, y: 24 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 24, y: 60 },
    },
    // Frame 2: FULL EXTENSION — maximum reach, body committed
    {
      head:      { x: 14, y: -96 },
      neck:      { x: 10, y: -78 },
      hip:       { x: 0, y: 0 },
      shoulderL: { x: -6, y: -76 },
      shoulderR: { x: 24, y: -76 },
      elbowL:    { x: -2, y: -60 },
      elbowR:    { x: 54, y: -74 },
      handL:     { x: 6, y: -72 },
      handR:     { x: 82, y: -74 },
      kneeL:     { x: -14, y: 26 },
      kneeR:     { x: 20, y: 24 },
      footL:     { x: -20, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 3: RECOVERY — pulling back
    {
      head:      { x: 6, y: -98 },
      neck:      { x: 4, y: -80 },
      hip:       { x: 0, y: 1 },
      shoulderL: { x: -12, y: -78 },
      shoulderR: { x: 16, y: -78 },
      elbowL:    { x: -4, y: -62 },
      elbowR:    { x: 36, y: -66 },
      handL:     { x: 10, y: -76 },
      handR:     { x: 44, y: -72 },
      kneeL:     { x: -16, y: 26 },
      kneeR:     { x: 18, y: 26 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 22, y: 60 },
    },
  ],

  // === KICK: Powerful roundhouse — chamber, sweep, extend, retract ===
  KICK: [
    // Frame 0: CHAMBER — knee lifts high, arms spread for balance
    {
      head:      { x: -6, y: -98 },
      neck:      { x: -4, y: -80 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -18, y: -78 },
      shoulderR: { x: 12, y: -78 },
      elbowL:    { x: -34, y: -66 },
      elbowR:    { x: 28, y: -62 },
      handL:     { x: -42, y: -52 },
      handR:     { x: 34, y: -48 },
      kneeL:     { x: -16, y: 28 },
      kneeR:     { x: 28, y: -8 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 22, y: 8 },
    },
    // Frame 1: SWEEP — leg extending, body leaning back
    {
      head:      { x: -10, y: -96 },
      neck:      { x: -8, y: -78 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -22, y: -76 },
      shoulderR: { x: 8, y: -76 },
      elbowL:    { x: -38, y: -62 },
      elbowR:    { x: 22, y: -58 },
      handL:     { x: -46, y: -48 },
      handR:     { x: 28, y: -44 },
      kneeL:     { x: -16, y: 28 },
      kneeR:     { x: 44, y: -10 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 68, y: -12 },
    },
    // Frame 2: FULL EXTENSION — massive reach, body counterbalanced
    {
      head:      { x: -18, y: -92 },
      neck:      { x: -14, y: -74 },
      hip:       { x: 0, y: 6 },
      shoulderL: { x: -26, y: -72 },
      shoulderR: { x: 4, y: -72 },
      elbowL:    { x: -42, y: -58 },
      elbowR:    { x: 16, y: -54 },
      handL:     { x: -50, y: -44 },
      handR:     { x: 22, y: -40 },
      kneeL:     { x: -18, y: 30 },
      kneeR:     { x: 48, y: -8 },
      footL:     { x: -26, y: 60 },
      footR:     { x: 88, y: -8 },
    },
    // Frame 3: RETRACT — leg coming back, body straightening
    {
      head:      { x: -6, y: -96 },
      neck:      { x: -4, y: -78 },
      hip:       { x: 0, y: 3 },
      shoulderL: { x: -18, y: -76 },
      shoulderR: { x: 12, y: -76 },
      elbowL:    { x: -30, y: -62 },
      elbowR:    { x: 26, y: -60 },
      handL:     { x: -36, y: -50 },
      handR:     { x: 32, y: -50 },
      kneeL:     { x: -16, y: 28 },
      kneeR:     { x: 24, y: 18 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 34, y: 46 },
    },
  ],

  // === SPECIAL: Power move — deep crouch, rise, explode, recover ===
  SPECIAL: [
    // Frame 0: POWER CROUCH — gathering energy
    {
      head:      { x: -4, y: -84 },
      neck:      { x: -3, y: -66 },
      hip:       { x: 0, y: 14 },
      shoulderL: { x: -18, y: -64 },
      shoulderR: { x: 18, y: -64 },
      elbowL:    { x: -28, y: -46 },
      elbowR:    { x: 10, y: -48 },
      handL:     { x: -22, y: -32 },
      handR:     { x: 2, y: -38 },
      kneeL:     { x: -22, y: 34 },
      kneeR:     { x: 22, y: 34 },
      footL:     { x: -28, y: 60 },
      footR:     { x: 26, y: 60 },
    },
    // Frame 1: RISING — body uncoils upward
    {
      head:      { x: 8, y: -98 },
      neck:      { x: 6, y: -80 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -12, y: -78 },
      shoulderR: { x: 20, y: -78 },
      elbowL:    { x: -6, y: -64 },
      elbowR:    { x: 42, y: -70 },
      handL:     { x: 8, y: -76 },
      handR:     { x: 56, y: -66 },
      kneeL:     { x: -18, y: 26 },
      kneeR:     { x: 20, y: 22 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 2: PEAK — full explosive extension
    {
      head:      { x: 16, y: -100 },
      neck:      { x: 12, y: -82 },
      hip:       { x: 0, y: -2 },
      shoulderL: { x: -6, y: -80 },
      shoulderR: { x: 24, y: -80 },
      elbowL:    { x: 0, y: -66 },
      elbowR:    { x: 54, y: -76 },
      handL:     { x: 12, y: -78 },
      handR:     { x: 80, y: -72 },
      kneeL:     { x: -22, y: 22 },
      kneeR:     { x: 24, y: 18 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 34, y: 60 },
    },
    // Frame 3: RECOVERY
    {
      head:      { x: 6, y: -98 },
      neck:      { x: 4, y: -80 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -12, y: -78 },
      shoulderR: { x: 16, y: -78 },
      elbowL:    { x: -6, y: -62 },
      elbowR:    { x: 34, y: -64 },
      handL:     { x: 8, y: -74 },
      handR:     { x: 42, y: -60 },
      kneeL:     { x: -18, y: 26 },
      kneeR:     { x: 18, y: 26 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 22, y: 60 },
    },
  ],

  // === BLOCK: Tight defensive guard ===
  BLOCK: [
    {
      head:      { x: -8, y: -92 },
      neck:      { x: -6, y: -74 },
      hip:       { x: 0, y: 8 },
      shoulderL: { x: -14, y: -72 },
      shoulderR: { x: 12, y: -72 },
      elbowL:    { x: -2, y: -62 },
      elbowR:    { x: 8, y: -62 },
      handL:     { x: 10, y: -82 },
      handR:     { x: 14, y: -54 },
      kneeL:     { x: -20, y: 30 },
      kneeR:     { x: 20, y: 30 },
      footL:     { x: -26, y: 60 },
      footR:     { x: 24, y: 60 },
    },
  ],

  // === HIT: Recoil from impact ===
  HIT: [
    // Impact — body snaps backward, arms flung
    {
      head:      { x: -18, y: -94 },
      neck:      { x: -14, y: -76 },
      hip:       { x: 0, y: 6 },
      shoulderL: { x: -24, y: -74 },
      shoulderR: { x: 2, y: -74 },
      elbowL:    { x: -40, y: -58 },
      elbowR:    { x: -12, y: -54 },
      handL:     { x: -48, y: -42 },
      handR:     { x: -20, y: -38 },
      kneeL:     { x: -6, y: 28 },
      kneeR:     { x: 18, y: 26 },
      footL:     { x: -10, y: 60 },
      footR:     { x: 24, y: 60 },
    },
    // Stagger — trying to recover
    {
      head:      { x: -12, y: -96 },
      neck:      { x: -10, y: -78 },
      hip:       { x: 0, y: 4 },
      shoulderL: { x: -20, y: -76 },
      shoulderR: { x: 8, y: -76 },
      elbowL:    { x: -34, y: -60 },
      elbowR:    { x: -2, y: -56 },
      handL:     { x: -38, y: -46 },
      handR:     { x: -8, y: -42 },
      kneeL:     { x: -12, y: 28 },
      kneeR:     { x: 16, y: 28 },
      footL:     { x: -16, y: 60 },
      footR:     { x: 22, y: 60 },
    },
  ],

  // === KO: Dramatic collapse ===
  KO: [
    // Stagger — arms loose
    {
      head:      { x: -22, y: -88 },
      neck:      { x: -16, y: -70 },
      hip:       { x: 0, y: 8 },
      shoulderL: { x: -26, y: -68 },
      shoulderR: { x: 0, y: -68 },
      elbowL:    { x: -40, y: -52 },
      elbowR:    { x: -12, y: -48 },
      handL:     { x: -48, y: -36 },
      handR:     { x: -20, y: -32 },
      kneeL:     { x: -4, y: 30 },
      kneeR:     { x: 20, y: 28 },
      footL:     { x: -8, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Falling — leaning way back
    {
      head:      { x: -34, y: -55 },
      neck:      { x: -26, y: -40 },
      hip:       { x: 0, y: 24 },
      shoulderL: { x: -30, y: -36 },
      shoulderR: { x: -18, y: -34 },
      elbowL:    { x: -42, y: -20 },
      elbowR:    { x: -14, y: -18 },
      handL:     { x: -50, y: -4 },
      handR:     { x: -10, y: 0 },
      kneeL:     { x: 10, y: 40 },
      kneeR:     { x: 26, y: 38 },
      footL:     { x: 18, y: 58 },
      footR:     { x: 38, y: 56 },
    },
    // On ground — collapsed
    {
      head:      { x: -44, y: 34 },
      neck:      { x: -32, y: 38 },
      hip:       { x: 0, y: 46 },
      shoulderL: { x: -36, y: 36 },
      shoulderR: { x: -28, y: 40 },
      elbowL:    { x: -48, y: 44 },
      elbowR:    { x: -18, y: 46 },
      handL:     { x: -58, y: 50 },
      handR:     { x: -12, y: 52 },
      kneeL:     { x: 20, y: 42 },
      kneeR:     { x: 30, y: 46 },
      footL:     { x: 38, y: 48 },
      footR:     { x: 50, y: 52 },
    },
  ],

  // === CROUCH: Low defensive stance ===
  CROUCH: [
    {
      head:      { x: 2, y: -55 },
      neck:      { x: 1, y: -42 },
      hip:       { x: 0, y: 18 },
      shoulderL: { x: -14, y: -40 },
      shoulderR: { x: 14, y: -40 },
      elbowL:    { x: -4, y: -28 },
      elbowR:    { x: 18, y: -32 },
      handL:     { x: 8, y: -44 },
      handR:     { x: 24, y: -48 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
  ],

  // === CROUCH_PUNCH: Low jab from crouch ===
  CROUCH_PUNCH: [
    // Frame 0: COIL — body turns, fist pulls back (crouching)
    {
      head:      { x: -4, y: -52 },
      neck:      { x: -3, y: -40 },
      hip:       { x: 0, y: 20 },
      shoulderL: { x: -16, y: -38 },
      shoulderR: { x: 10, y: -38 },
      elbowL:    { x: -6, y: -26 },
      elbowR:    { x: -2, y: -24 },
      handL:     { x: 6, y: -38 },
      handR:     { x: -8, y: -18 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 1: SNAP — fist shoots forward at low level
    {
      head:      { x: 6, y: -54 },
      neck:      { x: 4, y: -42 },
      hip:       { x: 0, y: 18 },
      shoulderL: { x: -10, y: -40 },
      shoulderR: { x: 18, y: -40 },
      elbowL:    { x: -4, y: -28 },
      elbowR:    { x: 40, y: -34 },
      handL:     { x: 8, y: -40 },
      handR:     { x: 64, y: -30 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 2: FULL EXTENSION — maximum reach, stays low
    {
      head:      { x: 8, y: -52 },
      neck:      { x: 6, y: -40 },
      hip:       { x: 0, y: 18 },
      shoulderL: { x: -8, y: -38 },
      shoulderR: { x: 20, y: -38 },
      elbowL:    { x: -2, y: -26 },
      elbowR:    { x: 46, y: -32 },
      handL:     { x: 6, y: -38 },
      handR:     { x: 74, y: -28 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 3: RECOVERY — pulling back to crouch guard
    {
      head:      { x: 2, y: -55 },
      neck:      { x: 1, y: -42 },
      hip:       { x: 0, y: 18 },
      shoulderL: { x: -14, y: -40 },
      shoulderR: { x: 14, y: -40 },
      elbowL:    { x: -4, y: -28 },
      elbowR:    { x: 30, y: -30 },
      handL:     { x: 8, y: -40 },
      handR:     { x: 38, y: -28 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
  ],

  // === CROUCH_KICK: Low sweep kick from crouch ===
  CROUCH_KICK: [
    // Frame 0: CHAMBER — leg lifts slightly, leaning back
    {
      head:      { x: -6, y: -54 },
      neck:      { x: -4, y: -42 },
      hip:       { x: 0, y: 20 },
      shoulderL: { x: -16, y: -40 },
      shoulderR: { x: 10, y: -40 },
      elbowL:    { x: -28, y: -30 },
      elbowR:    { x: 22, y: -28 },
      handL:     { x: -34, y: -18 },
      handR:     { x: 26, y: -16 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 20, y: 24 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 16, y: 38 },
    },
    // Frame 1: SWEEP — leg extending low along ground
    {
      head:      { x: -10, y: -50 },
      neck:      { x: -8, y: -38 },
      hip:       { x: 0, y: 22 },
      shoulderL: { x: -20, y: -36 },
      shoulderR: { x: 6, y: -36 },
      elbowL:    { x: -32, y: -26 },
      elbowR:    { x: 18, y: -24 },
      handL:     { x: -38, y: -14 },
      handR:     { x: 22, y: -12 },
      kneeL:     { x: -24, y: 38 },
      kneeR:     { x: 38, y: 40 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 62, y: 56 },
    },
    // Frame 2: FULL EXTENSION — foot sweeps maximum distance
    {
      head:      { x: -14, y: -48 },
      neck:      { x: -10, y: -36 },
      hip:       { x: 0, y: 24 },
      shoulderL: { x: -22, y: -34 },
      shoulderR: { x: 4, y: -34 },
      elbowL:    { x: -36, y: -24 },
      elbowR:    { x: 14, y: -22 },
      handL:     { x: -42, y: -12 },
      handR:     { x: 18, y: -10 },
      kneeL:     { x: -24, y: 40 },
      kneeR:     { x: 44, y: 44 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 80, y: 58 },
    },
    // Frame 3: RETRACT — leg pulling back to crouch
    {
      head:      { x: -4, y: -52 },
      neck:      { x: -3, y: -40 },
      hip:       { x: 0, y: 20 },
      shoulderL: { x: -16, y: -38 },
      shoulderR: { x: 10, y: -38 },
      elbowL:    { x: -26, y: -28 },
      elbowR:    { x: 20, y: -26 },
      handL:     { x: -30, y: -16 },
      handR:     { x: 24, y: -16 },
      kneeL:     { x: -24, y: 38 },
      kneeR:     { x: 22, y: 34 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 30, y: 50 },
    },
  ],

  // === COMBO_FINISHER_STRIKE: Explosive forward double-fist strike ===
  COMBO_FINISHER_STRIKE: [
    // Frame 0: Deep coil backward, both fists pulled back, knees bent
    {
      head:      { x: -12, y: -90 },
      neck:      { x: -8, y: -72 },
      hip:       { x: 0, y: 10 },
      shoulderL: { x: -20, y: -70 },
      shoulderR: { x: 10, y: -70 },
      elbowL:    { x: -30, y: -54 },
      elbowR:    { x: -14, y: -54 },
      handL:     { x: -24, y: -40 },
      handR:     { x: -20, y: -40 },
      kneeL:     { x: -22, y: 32 },
      kneeR:     { x: 22, y: 32 },
      footL:     { x: -28, y: 60 },
      footR:     { x: 26, y: 60 },
    },
    // Frame 1: Lunge forward, torso twisting, arms driving forward
    {
      head:      { x: 10, y: -96 },
      neck:      { x: 8, y: -78 },
      hip:       { x: 0, y: 4 },
      shoulderL: { x: -10, y: -76 },
      shoulderR: { x: 20, y: -76 },
      elbowL:    { x: 16, y: -66 },
      elbowR:    { x: 40, y: -70 },
      handL:     { x: 36, y: -64 },
      handR:     { x: 56, y: -68 },
      kneeL:     { x: -18, y: 28 },
      kneeR:     { x: 22, y: 24 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 2: Full extension — both arms punched forward, body leaning in
    {
      head:      { x: 18, y: -94 },
      neck:      { x: 14, y: -76 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -4, y: -74 },
      shoulderR: { x: 26, y: -74 },
      elbowL:    { x: 36, y: -68 },
      elbowR:    { x: 56, y: -72 },
      handL:     { x: 70, y: -66 },
      handR:     { x: 78, y: -70 },
      kneeL:     { x: -16, y: 26 },
      kneeR:     { x: 24, y: 22 },
      footL:     { x: -26, y: 60 },
      footR:     { x: 32, y: 60 },
    },
    // Frame 3: Follow-through, arms past center, body recovering
    {
      head:      { x: 12, y: -96 },
      neck:      { x: 8, y: -78 },
      hip:       { x: 0, y: 4 },
      shoulderL: { x: -8, y: -76 },
      shoulderR: { x: 18, y: -76 },
      elbowL:    { x: 20, y: -64 },
      elbowR:    { x: 38, y: -66 },
      handL:     { x: 40, y: -58 },
      handR:     { x: 50, y: -60 },
      kneeL:     { x: -18, y: 28 },
      kneeR:     { x: 20, y: 26 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 24, y: 60 },
    },
  ],

  // === COMBO_FINISHER_LAUNCH: Rising uppercut/knee launch ===
  COMBO_FINISHER_LAUNCH: [
    // Frame 0: Deep crouch wind-up, fist low, body compressed
    {
      head:      { x: -4, y: -80 },
      neck:      { x: -3, y: -62 },
      hip:       { x: 0, y: 16 },
      shoulderL: { x: -16, y: -60 },
      shoulderR: { x: 16, y: -60 },
      elbowL:    { x: -8, y: -42 },
      elbowR:    { x: 8, y: -36 },
      handL:     { x: 4, y: -54 },
      handR:     { x: 4, y: -22 },
      kneeL:     { x: -24, y: 36 },
      kneeR:     { x: 24, y: 36 },
      footL:     { x: -30, y: 60 },
      footR:     { x: 28, y: 60 },
    },
    // Frame 1: Explosive upward — body rising, lead arm driving up
    {
      head:      { x: 6, y: -100 },
      neck:      { x: 4, y: -82 },
      hip:       { x: 0, y: 4 },
      shoulderL: { x: -12, y: -80 },
      shoulderR: { x: 18, y: -80 },
      elbowL:    { x: -4, y: -66 },
      elbowR:    { x: 28, y: -96 },
      handL:     { x: 8, y: -78 },
      handR:     { x: 32, y: -112 },
      kneeL:     { x: -18, y: 26 },
      kneeR:     { x: 20, y: 18 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 26, y: 48 },
    },
    // Frame 2: Full vertical extension — fist at peak, body stretched tall
    {
      head:      { x: 8, y: -108 },
      neck:      { x: 6, y: -90 },
      hip:       { x: 0, y: -6 },
      shoulderL: { x: -10, y: -88 },
      shoulderR: { x: 20, y: -88 },
      elbowL:    { x: -6, y: -74 },
      elbowR:    { x: 30, y: -110 },
      handL:     { x: 6, y: -86 },
      handR:     { x: 34, y: -130 },
      kneeL:     { x: -16, y: 22 },
      kneeR:     { x: 22, y: 10 },
      footL:     { x: -22, y: 56 },
      footR:     { x: 28, y: 38 },
    },
    // Frame 3: Landing recovery, arms dropping
    {
      head:      { x: 4, y: -98 },
      neck:      { x: 3, y: -80 },
      hip:       { x: 0, y: 2 },
      shoulderL: { x: -14, y: -78 },
      shoulderR: { x: 16, y: -78 },
      elbowL:    { x: -6, y: -64 },
      elbowR:    { x: 24, y: -76 },
      handL:     { x: 8, y: -76 },
      handR:     { x: 28, y: -90 },
      kneeL:     { x: -18, y: 26 },
      kneeR:     { x: 20, y: 24 },
      footL:     { x: -24, y: 60 },
      footR:     { x: 24, y: 60 },
    },
  ],

  // === VICTORY: Celebration — loops ===
  VICTORY: [
    // Arms rising
    {
      head:      { x: 0, y: -104 },
      neck:      { x: 0, y: -86 },
      hip:       { x: 0, y: -4 },
      shoulderL: { x: -16, y: -84 },
      shoulderR: { x: 16, y: -84 },
      elbowL:    { x: -24, y: -100 },
      elbowR:    { x: 24, y: -100 },
      handL:     { x: -20, y: -116 },
      handR:     { x: 20, y: -116 },
      kneeL:     { x: -14, y: 24 },
      kneeR:     { x: 14, y: 24 },
      footL:     { x: -20, y: 60 },
      footR:     { x: 20, y: 60 },
    },
    // Pump fists — triumphant
    {
      head:      { x: 0, y: -106 },
      neck:      { x: 0, y: -88 },
      hip:       { x: 0, y: -6 },
      shoulderL: { x: -18, y: -86 },
      shoulderR: { x: 18, y: -86 },
      elbowL:    { x: -30, y: -106 },
      elbowR:    { x: 30, y: -106 },
      handL:     { x: -34, y: -122 },
      handR:     { x: 34, y: -122 },
      kneeL:     { x: -16, y: 22 },
      kneeR:     { x: 16, y: 22 },
      footL:     { x: -22, y: 60 },
      footR:     { x: 22, y: 60 },
    },
    // Wide celebration
    {
      head:      { x: 0, y: -104 },
      neck:      { x: 0, y: -86 },
      hip:       { x: 0, y: -2 },
      shoulderL: { x: -18, y: -84 },
      shoulderR: { x: 18, y: -84 },
      elbowL:    { x: -36, y: -98 },
      elbowR:    { x: 36, y: -98 },
      handL:     { x: -44, y: -112 },
      handR:     { x: 44, y: -112 },
      kneeL:     { x: -18, y: 24 },
      kneeR:     { x: 18, y: 24 },
      footL:     { x: -26, y: 60 },
      footR:     { x: 26, y: 60 },
    },
  ],
};

// Helper to interpolate between two poses
export function lerpPose(poseA, poseB, t) {
  const result = {};
  for (const joint in poseA) {
    result[joint] = {
      x: poseA[joint].x + (poseB[joint].x - poseA[joint].x) * t,
      y: poseA[joint].y + (poseB[joint].y - poseA[joint].y) * t,
    };
  }
  return result;
}
