// Each character has unique stats and a special move type.
// Special types are implemented in Fighter.updateState().

export const FIGHTERS = [
  {
    id: 'swift',
    name: 'Swift',
    color: 0xffffff,
    description: 'Balanced fighter with a quick lunge.',
    moveSpeed: 300,
    jumpVelocity: -650,
    punchDamage: 8,
    punchRange: 60,
    kickDamage: 14,
    kickRange: 80,
    specialDamage: 22,
    specialRange: 100,
    specialType: 'lunge',
    specialName: 'Dash Strike',
    specialDuration: 500,
    visual: {
      headRadius: 1.0,
      lineWidth: 0.85,
      limbScale: 1.05,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'headband', joint: 'head', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','PUNCH','KICK'], damageScale: [1,1.1,1.3], durationScale: [1,0.7,0.85], finisher: true, finisherAnim: 'launch' },
        { sequence: ['PUNCH','KICK'], damageScale: [1,1.2], durationScale: [1,0.8], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH','PUNCH'], damageScale: [1,1.0,1.2], durationScale: [1,0.75,0.8], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.35,
    },
  },
  {
    id: 'titan',
    name: 'Titan',
    color: 0x00ffff,
    description: 'Slow powerhouse. Ground pound shakes the arena.',
    moveSpeed: 220,
    jumpVelocity: -520,
    punchDamage: 11,
    punchRange: 65,
    kickDamage: 19,
    kickRange: 85,
    specialDamage: 28,
    specialRange: 120,
    specialType: 'groundPound',
    specialName: 'Ground Pound',
    specialDuration: 900,
    visual: {
      headRadius: 1.2,
      lineWidth: 1.4,
      limbScale: 0.92,
      shoulderWidth: 1.3,
      headShape: 'circle',
      accessories: [{ type: 'shoulderPads', joint: 'shoulderL', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','KICK'], damageScale: [1,1.4], durationScale: [1,0.9], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','KICK'], damageScale: [1,1.5], durationScale: [1,0.9], finisher: true, finisherAnim: 'launch' },
      ],
      cancelWindowRatio: 0.25,
    },
  },
  {
    id: 'shadow',
    name: 'Shadow',
    color: 0xbb44ff,
    description: 'Fragile but lightning fast. Teleports behind foes.',
    moveSpeed: 380,
    jumpVelocity: -700,
    punchDamage: 7,
    punchRange: 55,
    kickDamage: 12,
    kickRange: 75,
    specialDamage: 18,
    specialRange: 60,
    specialType: 'teleport',
    specialName: 'Shadow Step',
    specialDuration: 550,
    maxHealth: 80,
    visual: {
      headRadius: 0.85,
      lineWidth: 0.75,
      limbScale: 1.08,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'scarf', joint: 'neck', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','PUNCH','PUNCH'], damageScale: [1,1.0,1.2], durationScale: [1,0.65,0.6], finisher: true, finisherAnim: 'strike' },
        { sequence: ['PUNCH','KICK'], damageScale: [1,1.2], durationScale: [1,0.75], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.1], durationScale: [1,0.7], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.35,
    },
  },
  {
    id: 'blaze',
    name: 'Blaze',
    color: 0xff6600,
    description: 'Aggressive brawler with a fiery uppercut.',
    moveSpeed: 280,
    jumpVelocity: -620,
    punchDamage: 9,
    punchRange: 58,
    kickDamage: 15,
    kickRange: 78,
    specialDamage: 24,
    specialRange: 70,
    specialType: 'uppercut',
    specialName: 'Fire Uppercut',
    specialDuration: 650,
    visual: {
      headRadius: 1.0,
      lineWidth: 1.0,
      limbScale: 1.0,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'flameHair', joint: 'head', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','PUNCH','KICK'], damageScale: [1,1.1,1.4], durationScale: [1,0.75,0.85], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.3], durationScale: [1,0.8], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.3,
    },
  },
  {
    id: 'frost',
    name: 'Frost',
    color: 0x66ccff,
    description: 'Cool and collected. Ice slide covers distance fast.',
    moveSpeed: 260,
    jumpVelocity: -600,
    punchDamage: 8,
    punchRange: 60,
    kickDamage: 14,
    kickRange: 80,
    specialDamage: 20,
    specialRange: 130,
    specialType: 'slide',
    specialName: 'Ice Slide',
    specialDuration: 550,
    visual: {
      headRadius: 1.0,
      lineWidth: 1.0,
      limbScale: 1.0,
      shoulderWidth: 1.0,
      headShape: 'angular',
      accessories: [{ type: 'iceShard', joint: 'shoulderL', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','KICK'], damageScale: [1,1.3], durationScale: [1,0.85], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.2], durationScale: [1,0.8], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.28,
    },
  },
  {
    id: 'thunder',
    name: 'Thunder',
    color: 0xffff00,
    description: 'Electrifying strikes. Lightning drop from above.',
    moveSpeed: 270,
    jumpVelocity: -680,
    punchDamage: 9,
    punchRange: 60,
    kickDamage: 16,
    kickRange: 82,
    specialDamage: 26,
    specialRange: 90,
    specialType: 'lightningDrop',
    specialName: 'Lightning Drop',
    specialDuration: 800,
    visual: {
      headRadius: 1.0,
      lineWidth: 1.1,
      limbScale: 1.0,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'boltMark', joint: 'neck', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','KICK','PUNCH'], damageScale: [1,1.1,1.3], durationScale: [1,0.8,0.75], finisher: true, finisherAnim: 'strike' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.2], durationScale: [1,0.8], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.3,
    },
  },
  {
    id: 'viper',
    name: 'Viper',
    color: 0x44ff44,
    description: 'Quick multi-hit combos. Rapid dash flurry.',
    moveSpeed: 330,
    jumpVelocity: -640,
    punchDamage: 6,
    punchRange: 55,
    kickDamage: 10,
    kickRange: 70,
    specialDamage: 8,
    specialRange: 80,
    specialType: 'flurry',
    specialName: 'Viper Flurry',
    specialHits: 4,
    specialDuration: 700,
    visual: {
      headRadius: 0.9,
      lineWidth: 0.8,
      limbScale: 1.1,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'tail', joint: 'hip', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','PUNCH','PUNCH','KICK'], damageScale: [1,1.0,1.1,1.4], durationScale: [1,0.6,0.55,0.7], finisher: true, finisherAnim: 'launch' },
        { sequence: ['PUNCH','KICK','PUNCH'], damageScale: [1,1.1,1.3], durationScale: [1,0.7,0.65], finisher: true, finisherAnim: 'strike' },
        { sequence: ['KICK','PUNCH','PUNCH'], damageScale: [1,1.0,1.2], durationScale: [1,0.65,0.6], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.38,
    },
  },
  {
    id: 'golem',
    name: 'Golem',
    color: 0xaa8855,
    description: 'Immovable wall. Absorbs a hit during special.',
    moveSpeed: 180,
    jumpVelocity: -450,
    punchDamage: 13,
    punchRange: 70,
    kickDamage: 22,
    kickRange: 90,
    specialDamage: 30,
    specialRange: 90,
    specialType: 'armorSmash',
    specialName: 'Armor Smash',
    specialDuration: 800,
    maxHealth: 120,
    visual: {
      headRadius: 1.35,
      lineWidth: 1.6,
      limbScale: 0.88,
      shoulderWidth: 1.4,
      headShape: 'flat',
      accessories: [{ type: 'armGuards', joint: 'elbowL', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','PUNCH'], damageScale: [1,1.5], durationScale: [1,0.9], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.4], durationScale: [1,0.85], finisher: true, finisherAnim: 'launch' },
      ],
      cancelWindowRatio: 0.22,
    },
  },
  {
    id: 'phantom',
    name: 'Phantom',
    color: 0xddddff,
    description: 'Floaty and evasive. Spinning whirlwind attack.',
    moveSpeed: 290,
    jumpVelocity: -750,
    punchDamage: 7,
    punchRange: 55,
    kickDamage: 12,
    kickRange: 75,
    specialDamage: 16,
    specialRange: 110,
    specialType: 'whirlwind',
    specialName: 'Whirlwind',
    specialDuration: 650,
    visual: {
      headRadius: 0.9,
      lineWidth: 0.7,
      limbScale: 1.06,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'wisps', joint: 'hip', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','KICK','KICK'], damageScale: [1,1.1,1.3], durationScale: [1,0.8,0.75], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','PUNCH'], damageScale: [1,1.2], durationScale: [1,0.8], finisher: true, finisherAnim: 'strike' },
      ],
      cancelWindowRatio: 0.3,
    },
  },
  {
    id: 'nova',
    name: 'Nova',
    color: 0xff3366,
    description: 'Glass cannon. Massive explosive burst.',
    moveSpeed: 260,
    jumpVelocity: -600,
    punchDamage: 10,
    punchRange: 58,
    kickDamage: 16,
    kickRange: 78,
    specialDamage: 38,
    specialRange: 140,
    specialType: 'explosion',
    specialName: 'Nova Burst',
    specialDuration: 700,
    maxHealth: 70,
    visual: {
      headRadius: 1.0,
      lineWidth: 1.0,
      limbScale: 0.95,
      shoulderWidth: 1.0,
      headShape: 'circle',
      accessories: [{ type: 'halo', joint: 'head', offsetX: 0, offsetY: 0 }],
    },
    combos: {
      chains: [
        { sequence: ['PUNCH','KICK'], damageScale: [1,1.5], durationScale: [1,0.85], finisher: true, finisherAnim: 'launch' },
        { sequence: ['KICK','KICK'], damageScale: [1,1.4], durationScale: [1,0.9], finisher: true, finisherAnim: 'launch' },
      ],
      cancelWindowRatio: 0.28,
    },
  },
];

// Keep backwards-compatible exports for existing code
export const FIGHTER_DATA = {
  balanced: FIGHTERS[0],
  heavy: FIGHTERS[1],
};
